### PR TITLE
move to es modules and node testing

### PR DESCRIPTION
**Pull request by hawkrives**

### CODE REVIEW

**Comment by hawkrives** [comment]
tomorrow I'll add types

**Comment by drewvolz** [comment]
Thoughts on using [ts-node](https://github.com/TypeStrong/ts-node)?

**Comment by hawkrives** [comment]
Maybe. I was hoping to avoid a compile step… but I can if we'd prefer.

**Review by drewvolz — APPROVED** [review]

**Comment by hawkrives** [comment]
@drewvolz I added types :-)

**Review by drewvolz — APPROVED** [review]

**Pull request merged**
